openapi: 3.0.0
info:
  version: 1.0.0
  title: BoostTeams API docs
  description: BoostTeams의 API 문서입니다
  license:
    name: MIT
servers:
  - url: 'http://localhost:4000/'
paths:
  /api/auth: !<tag:yaml.org,2002:js/undefined> ''
